/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040101
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_TransFE_NativeWrapper(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_TransFE_NativeWrapper(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_TransFE_NativeWrapper(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } } while (0)

/* SWIG Errors applicable to all language modules, values are reserved from -1 to -99 */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <algorithm>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>


SWIGINTERN void SWIG_CSharpException(int code, const char *msg) {
  if (code == SWIG_ValueError) {
    SWIG_CSharpExceptionArgumentCodes exception_code = SWIG_CSharpArgumentOutOfRangeException;
    SWIG_CSharpSetPendingExceptionArgument(exception_code, msg, 0);
  } else {
    SWIG_CSharpExceptionCodes exception_code = SWIG_CSharpApplicationException;
    switch(code) {
    case SWIG_MemoryError:
      exception_code = SWIG_CSharpOutOfMemoryException;
      break;
    case SWIG_IndexError:
      exception_code = SWIG_CSharpIndexOutOfRangeException;
      break;
    case SWIG_DivisionByZero:
      exception_code = SWIG_CSharpDivideByZeroException;
      break;
    case SWIG_IOError:
      exception_code = SWIG_CSharpIOException;
      break;
    case SWIG_OverflowError:
      exception_code = SWIG_CSharpOverflowException;
      break;
    case SWIG_RuntimeError:
    case SWIG_TypeError:
    case SWIG_SyntaxError:
    case SWIG_SystemError:
    case SWIG_UnknownError:
    default:
      exception_code = SWIG_CSharpApplicationException;
      break;
    }
    SWIG_CSharpSetPendingException(exception_code, msg);
  }
}


#include <typeinfo>
#include <stdexcept>


#include <utility>


#include "../TransFE/feprog.h"
#include "../TransFE/MeshDB/mesh.h"
#include "../TransFE/MeshDB/meshentity.h"
#include "../TransFE/MeshDB/meshvertex.h"
#include "../TransFE/MeshDB/meshedge.h"
#include "../TransFE/MeshDB/meshface.h"
#include "../TransFE/MeshDB/node.h"
#include "../TransFE/dof.h"


struct SWIG_null_deleter {
  void operator() (void const *) const {
  }
};
#define SWIG_NO_NULL_DELETER_0 , SWIG_null_deleter()
#define SWIG_NO_NULL_DELETER_1
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_NEW
#define SWIG_NO_NULL_DELETER_SWIG_POINTER_OWN


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void SWIGSTDCALL CSharp_FEProg_theAnalysis_set(void * jarg1, void * jarg2) {
  FEProg *arg1 = (FEProg *) 0 ;
  MagAxiStaticAnalysis *arg2 = (MagAxiStaticAnalysis *) 0 ;
  
  arg1 = (FEProg *)jarg1; 
  arg2 = (MagAxiStaticAnalysis *)jarg2; 
  if (arg1) (arg1)->theAnalysis = arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_FEProg_theAnalysis_get(void * jarg1) {
  void * jresult ;
  FEProg *arg1 = (FEProg *) 0 ;
  MagAxiStaticAnalysis *result = 0 ;
  
  arg1 = (FEProg *)jarg1; 
  result = (MagAxiStaticAnalysis *) ((arg1)->theAnalysis);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_FEProg() {
  void * jresult ;
  FEProg *result = 0 ;
  
  result = (FEProg *)new FEProg();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_FEProg(void * jarg1) {
  FEProg *arg1 = (FEProg *) 0 ;
  
  arg1 = (FEProg *)jarg1; 
  delete arg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_FEProg_run_FEA(void * jarg1, const char * jarg2, int jarg3) {
  void * jresult ;
  FEProg *arg1 = (FEProg *) 0 ;
  std::string *arg2 = 0 ;
  int arg3 ;
  std::shared_ptr< Mesh > result;
  
  arg1 = (FEProg *)jarg1; 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return 0;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  arg3 = (int)jarg3; 
  result = (arg1)->run_FEA((std::string const &)*arg2,arg3);
  jresult = result ? new std::shared_ptr< Mesh >(result) : 0; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Mesh() {
  void * jresult ;
  Mesh *result = 0 ;
  
  result = (Mesh *)new Mesh();
  
  jresult = result ? new std::shared_ptr<  Mesh >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Mesh(void * jarg1) {
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_newRegion(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  MeshRegion *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = (MeshRegion *) &(arg1)->newRegion();
  jresult = new std::shared_ptr<  MeshRegion >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_newFace(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  MeshFace *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = (MeshFace *) &(arg1)->newFace();
  jresult = new std::shared_ptr<  MeshFace >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_newEdge(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  MeshEdge *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = (MeshEdge *) &(arg1)->newEdge();
  jresult = new std::shared_ptr<  MeshEdge >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_newVertex(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  MeshVertex *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = (MeshVertex *) &(arg1)->newVertex();
  jresult = new std::shared_ptr<  MeshVertex >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_newNode(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  Node *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Node *) &(arg1)->newNode();
  jresult = new std::shared_ptr<  Node >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getRegion(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  MeshRegion *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshRegion *) &((Mesh const *)arg1)->getRegion(arg2);
  jresult = new std::shared_ptr<  MeshRegion >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getFace(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  MeshFace *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshFace *) &((Mesh const *)arg1)->getFace(arg2);
  jresult = new std::shared_ptr<  MeshFace >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getEdge(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  MeshEdge *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshEdge *) &((Mesh const *)arg1)->getEdge(arg2);
  jresult = new std::shared_ptr<  MeshEdge >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getVertex(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  MeshVertex *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshVertex *) &((Mesh const *)arg1)->getVertex(arg2);
  jresult = new std::shared_ptr<  MeshVertex >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getNode(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  Node *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (Node *) &((Mesh const *)arg1)->getNode(arg2);
  jresult = new std::shared_ptr<  Node >(result SWIG_NO_NULL_DELETER_0); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getFaces(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< MeshFace * > > result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->getFaces();
  jresult = new std::vector< MeshFace * >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getNodes(void * jarg1) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< Node * > > result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->getNodes();
  jresult = new std::vector< Node * >(result); 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Mesh_numRegions(void * jarg1) {
  unsigned long jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->numRegions();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Mesh_numFaces(void * jarg1) {
  unsigned long jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->numFaces();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Mesh_numEdges(void * jarg1) {
  unsigned long jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->numEdges();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Mesh_numVertexes(void * jarg1) {
  unsigned long jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->numVertexes();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Mesh_numNodes(void * jarg1) {
  unsigned long jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Mesh const *)arg1)->numNodes();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Mesh_readMesh(void * jarg1, const char * jarg2) {
  Mesh *arg1 = (Mesh *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  (arg1)->readMesh((std::string const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_Mesh_readAttributes(void * jarg1, const char * jarg2) {
  Mesh *arg1 = (Mesh *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Mesh > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  (arg1)->readAttributes((std::string const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Mesh_getGeomEntity(void * jarg1, int jarg2) {
  void * jresult ;
  Mesh *arg1 = (Mesh *) 0 ;
  int arg2 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  GeomEntity *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (int)jarg2; 
  result = (GeomEntity *)((Mesh const *)arg1)->getGeomEntity(arg2);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Mesh_writeMesh(void * jarg1, const char * jarg2) {
  Mesh *arg1 = (Mesh *) 0 ;
  std::string *arg2 = 0 ;
  std::shared_ptr< Mesh const > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Mesh > *)jarg1;
  arg1 = (Mesh *)(smartarg1 ? smartarg1->get() : 0); 
  if (!jarg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "null string", 0);
    return ;
  }
  std::string arg2_str(jarg2);
  arg2 = &arg2_str; 
  ((Mesh const *)arg1)->writeMesh((std::string const &)*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MeshEntity(void * jarg1) {
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MeshEntity_get_dimensions(void * jarg1) {
  int jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity const > *smartarg1 = 0 ;
  int result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = (int)((MeshEntity const *)arg1)->get_dimensions();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEntity_getNode(void * jarg1) {
  void * jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity const > *smartarg1 = 0 ;
  Node *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = (Node *)((MeshEntity const *)arg1)->getNode();
  
  jresult = result ? new std::shared_ptr<  Node >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshEntity_setNode(void * jarg1, void * jarg2) {
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  Node *arg2 = 0 ;
  std::shared_ptr< MeshEntity > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (Node *)(((std::shared_ptr<  Node > *)jarg2) ? ((std::shared_ptr<  Node > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "Node & reference is null", 0);
    return ;
  } 
  (arg1)->setNode(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEntity_getClassification(void * jarg1) {
  void * jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity > *smartarg1 = 0 ;
  GeomEntity *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = (GeomEntity *)(arg1)->getClassification();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshEntity_setClassification(void * jarg1, void * jarg2) {
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  GeomEntity *arg2 = 0 ;
  std::shared_ptr< MeshEntity > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (GeomEntity *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "GeomEntity & is null", 0);
    return ;
  } 
  (arg1)->setClassification(*arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_MeshEntity_getClassificationID(void * jarg1) {
  int jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity const > *smartarg1 = 0 ;
  int result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = (int)((MeshEntity const *)arg1)->getClassificationID();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEntity_getNodes(void * jarg1) {
  void * jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< Node * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshEntity const *)arg1)->getNodes();
  jresult = new std::vector< Node * >(result); 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MeshEntity_getID(void * jarg1) {
  unsigned long jresult ;
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  std::shared_ptr< MeshEntity const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshEntity const *)arg1)->getID();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshEntity_setID(void * jarg1, unsigned long jarg2) {
  MeshEntity *arg1 = (MeshEntity *) 0 ;
  size_t arg2 ;
  std::shared_ptr< MeshEntity > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEntity > *)jarg1;
  arg1 = (MeshEntity *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  (arg1)->setID(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MeshVertex() {
  void * jresult ;
  MeshVertex *result = 0 ;
  
  result = (MeshVertex *)new MeshVertex();
  
  jresult = result ? new std::shared_ptr<  MeshVertex >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MeshVertex(void * jarg1) {
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  std::shared_ptr< MeshVertex > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshVertex_Edges(void * jarg1) {
  void * jresult ;
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  std::shared_ptr< MeshVertex const > *smartarg1 = 0 ;
  std::vector< MeshEdge * > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::vector< MeshEdge * > *) &((MeshVertex const *)arg1)->Edges();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshVertex_getEdge(void * jarg1, int jarg2) {
  void * jresult ;
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  int arg2 ;
  std::shared_ptr< MeshVertex const > *smartarg1 = 0 ;
  MeshEdge *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (int)jarg2; 
  result = (MeshEdge *)((MeshVertex const *)arg1)->getEdge(arg2);
  
  jresult = result ? new std::shared_ptr<  MeshEdge >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshVertex_addEdge(void * jarg1, void * jarg2) {
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  MeshEdge *arg2 = 0 ;
  std::shared_ptr< MeshVertex > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshEdge *)(((std::shared_ptr<  MeshEdge > *)jarg2) ? ((std::shared_ptr<  MeshEdge > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshEdge & reference is null", 0);
    return ;
  } 
  (arg1)->addEdge(*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MeshVertex_numEdges(void * jarg1) {
  unsigned long jresult ;
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  std::shared_ptr< MeshVertex const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshVertex const *)arg1)->numEdges();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MeshVertex_get_dimensions(void * jarg1) {
  int jresult ;
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  std::shared_ptr< MeshVertex const > *smartarg1 = 0 ;
  int result;
  
  
  smartarg1 = (std::shared_ptr< const MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  result = (int)((MeshVertex const *)arg1)->get_dimensions();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshVertex_getNodes(void * jarg1) {
  void * jresult ;
  MeshVertex *arg1 = (MeshVertex *) 0 ;
  std::shared_ptr< MeshVertex const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< Node * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshVertex > *)jarg1;
  arg1 = (MeshVertex *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshVertex const *)arg1)->getNodes();
  jresult = new std::vector< Node * >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MeshEdge() {
  void * jresult ;
  MeshEdge *result = 0 ;
  
  result = (MeshEdge *)new MeshEdge();
  
  jresult = result ? new std::shared_ptr<  MeshEdge >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MeshEdge(void * jarg1) {
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  std::shared_ptr< MeshEdge > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_getVertex(void * jarg1, int jarg2) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  int arg2 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  MeshVertex *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (int)jarg2; 
  result = (MeshVertex *)((MeshEdge const *)arg1)->getVertex(arg2);
  
  jresult = result ? new std::shared_ptr< const MeshVertex >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_Faces(void * jarg1) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  std::vector< MeshFace * > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::vector< MeshFace * > *) &((MeshEdge const *)arg1)->Faces();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_getFace(void * jarg1, int jarg2) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  int arg2 ;
  std::shared_ptr< MeshEdge > *smartarg1 = 0 ;
  MeshFace *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (int)jarg2; 
  result = (MeshFace *)(arg1)->getFace(arg2);
  
  jresult = result ? new std::shared_ptr<  MeshFace >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshEdge_addVertex(void * jarg1, void * jarg2, int jarg3) {
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  MeshVertex *arg2 = 0 ;
  int arg3 ;
  std::shared_ptr< MeshEdge > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshVertex *)(((std::shared_ptr<  MeshVertex > *)jarg2) ? ((std::shared_ptr<  MeshVertex > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshVertex & reference is null", 0);
    return ;
  } 
  arg3 = (int)jarg3; 
  (arg1)->addVertex(*arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshEdge_addFace(void * jarg1, void * jarg2) {
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  MeshFace *arg2 = 0 ;
  std::shared_ptr< MeshEdge > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshFace *)(((std::shared_ptr<  MeshFace > *)jarg2) ? ((std::shared_ptr<  MeshFace > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshFace & reference is null", 0);
    return ;
  } 
  (arg1)->addFace(*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_otherVertex(void * jarg1, void * jarg2) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  MeshVertex *arg2 = 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  MeshVertex *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshVertex *)(((std::shared_ptr< const MeshVertex > *)jarg2) ? ((std::shared_ptr< const MeshVertex > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshVertex const & reference is null", 0);
    return 0;
  } 
  result = (MeshVertex *)((MeshEdge const *)arg1)->otherVertex((MeshVertex const &)*arg2);
  
  jresult = result ? new std::shared_ptr<  MeshVertex >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MeshEdge_isConnected__SWIG_0(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  MeshEdge *arg2 = 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  bool result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshEdge *)(((std::shared_ptr< const MeshEdge > *)jarg2) ? ((std::shared_ptr< const MeshEdge > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshEdge const & reference is null", 0);
    return 0;
  } 
  result = (bool)((MeshEdge const *)arg1)->isConnected((MeshEdge const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_MeshEdge_isConnected__SWIG_1(void * jarg1, void * jarg2) {
  unsigned int jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  MeshVertex *arg2 = 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  bool result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshVertex *)(((std::shared_ptr< const MeshVertex > *)jarg2) ? ((std::shared_ptr< const MeshVertex > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshVertex const & reference is null", 0);
    return 0;
  } 
  result = (bool)((MeshEdge const *)arg1)->isConnected((MeshVertex const &)*arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_getNodes(void * jarg1) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< Node * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshEdge const *)arg1)->getNodes();
  jresult = new std::vector< Node * >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshEdge_getVertices(void * jarg1) {
  void * jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< MeshVertex const * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshEdge const *)arg1)->getVertices();
  jresult = new std::vector< MeshVertex const * >(result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MeshEdge_get_dimensions(void * jarg1) {
  int jresult ;
  MeshEdge *arg1 = (MeshEdge *) 0 ;
  std::shared_ptr< MeshEdge const > *smartarg1 = 0 ;
  int result;
  
  
  smartarg1 = (std::shared_ptr< const MeshEdge > *)jarg1;
  arg1 = (MeshEdge *)(smartarg1 ? smartarg1->get() : 0); 
  result = (int)((MeshEdge const *)arg1)->get_dimensions();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_MeshFace() {
  void * jresult ;
  MeshFace *result = 0 ;
  
  result = (MeshFace *)new MeshFace();
  
  jresult = result ? new std::shared_ptr<  MeshFace >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_MeshFace(void * jarg1) {
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_Edges(void * jarg1) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace const > *smartarg1 = 0 ;
  std::vector< MeshEdge * > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::vector< MeshEdge * > *) &((MeshFace const *)arg1)->Edges();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_getEdge(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  size_t arg2 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  MeshEdge *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshEdge *)(arg1)->getEdge(arg2);
  
  jresult = result ? new std::shared_ptr<  MeshEdge >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_getRegion(void * jarg1, unsigned long jarg2) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  size_t arg2 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  MeshRegion *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  result = (MeshRegion *)(arg1)->getRegion(arg2);
  
  jresult = result ? new std::shared_ptr<  MeshRegion >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshFace_addEdge(void * jarg1, void * jarg2) {
  MeshFace *arg1 = (MeshFace *) 0 ;
  MeshEdge *arg2 = 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshEdge *)(((std::shared_ptr<  MeshEdge > *)jarg2) ? ((std::shared_ptr<  MeshEdge > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshEdge & reference is null", 0);
    return ;
  } 
  (arg1)->addEdge(*arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshFace_addRegion(void * jarg1, void * jarg2) {
  MeshFace *arg1 = (MeshFace *) 0 ;
  MeshRegion *arg2 = 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  
  arg2 = (MeshRegion *)(((std::shared_ptr<  MeshRegion > *)jarg2) ? ((std::shared_ptr<  MeshRegion > *)jarg2)->get() : 0);
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "MeshRegion & reference is null", 0);
    return ;
  } 
  (arg1)->addRegion(*arg2);
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_MeshFace_numEdges(void * jarg1) {
  unsigned long jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = (arg1)->numEdges();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_MeshFace_area(void * jarg1) {
  double jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  double result;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = (double)(arg1)->area();
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_MeshFace_get_dimensions(void * jarg1) {
  int jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace const > *smartarg1 = 0 ;
  int result;
  
  
  smartarg1 = (std::shared_ptr< const MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = (int)((MeshFace const *)arg1)->get_dimensions();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_getNodes(void * jarg1) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< Node * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshFace const *)arg1)->getNodes();
  jresult = new std::vector< Node * >(result); 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_getVertices(void * jarg1) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace const > *smartarg1 = 0 ;
  SwigValueWrapper< std::vector< MeshVertex const * > > result;
  
  
  smartarg1 = (std::shared_ptr< const MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((MeshFace const *)arg1)->getVertices();
  jresult = new std::vector< MeshVertex const * >(result); 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_MeshFace_MeshEdges_set(void * jarg1, void * jarg2) {
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::vector< MeshEdge * > *arg2 = (std::vector< MeshEdge * > *) 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (std::vector< MeshEdge * > *)jarg2; 
  if (arg1) (arg1)->MeshEdges = *arg2;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_MeshFace_MeshEdges_get(void * jarg1) {
  void * jresult ;
  MeshFace *arg1 = (MeshFace *) 0 ;
  std::shared_ptr< MeshFace > *smartarg1 = 0 ;
  std::vector< MeshEdge * > *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  MeshFace > *)jarg1;
  arg1 = (MeshFace *)(smartarg1 ? smartarg1->get() : 0); 
  result = (std::vector< MeshEdge * > *)& ((arg1)->MeshEdges);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_new_Node() {
  void * jresult ;
  Node *result = 0 ;
  
  result = (Node *)new Node();
  
  jresult = result ? new std::shared_ptr<  Node >(result SWIG_NO_NULL_DELETER_1) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_delete_Node(void * jarg1) {
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  (void)arg1; delete smartarg1;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Node_x(void * jarg1) {
  double jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  double result;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = (double)((Node const *)arg1)->x();
  jresult = result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Node_y(void * jarg1) {
  double jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  double result;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = (double)((Node const *)arg1)->y();
  jresult = result; 
  return jresult;
}


SWIGEXPORT double SWIGSTDCALL CSharp_Node_z(void * jarg1) {
  double jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  double result;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = (double)((Node const *)arg1)->z();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Node_pt__SWIG_0(void * jarg1, void * jarg2) {
  Node *arg1 = (Node *) 0 ;
  point *arg2 = 0 ;
  std::shared_ptr< Node > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (point *)jarg2;
  if (!arg2) {
    SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException, "point const & is null", 0);
    return ;
  } 
  (arg1)->pt((point const &)*arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Node_pt__SWIG_1(void * jarg1) {
  void * jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  point *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = (point *) &((Node const *)arg1)->pt();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_Node_getID(void * jarg1) {
  unsigned long jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  size_t result;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = ((Node const *)arg1)->getID();
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Node_setID(void * jarg1, unsigned long jarg2) {
  Node *arg1 = (Node *) 0 ;
  size_t arg2 ;
  std::shared_ptr< Node > *smartarg1 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  arg2 = (size_t)jarg2; 
  (arg1)->setID(arg2);
}


SWIGEXPORT void * SWIGSTDCALL CSharp_Node_getParent(void * jarg1) {
  void * jresult ;
  Node *arg1 = (Node *) 0 ;
  std::shared_ptr< Node const > *smartarg1 = 0 ;
  MeshEntity *result = 0 ;
  
  
  smartarg1 = (std::shared_ptr< const Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  result = (MeshEntity *)((Node const *)arg1)->getParent();
  
  jresult = result ? new std::shared_ptr<  MeshEntity >(result SWIG_NO_NULL_DELETER_0) : 0;
  
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_Node_setParent(void * jarg1, void * jarg2) {
  Node *arg1 = (Node *) 0 ;
  MeshEntity *arg2 = (MeshEntity *) 0 ;
  std::shared_ptr< Node > *smartarg1 = 0 ;
  std::shared_ptr< MeshEntity > *smartarg2 = 0 ;
  
  
  smartarg1 = (std::shared_ptr<  Node > *)jarg1;
  arg1 = (Node *)(smartarg1 ? smartarg1->get() : 0); 
  
  smartarg2 = (std::shared_ptr<  MeshEntity > *)jarg2;
  arg2 = (MeshEntity *)(smartarg2 ? smartarg2->get() : 0); 
  (arg1)->setParent(arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_ndof_set(unsigned long jarg1) {
  size_t arg1 ;
  
  arg1 = (size_t)jarg1; 
  ndof = arg1;
}


SWIGEXPORT unsigned long SWIGSTDCALL CSharp_ndof_get() {
  unsigned long jresult ;
  size_t result;
  
  result = ndof;
  jresult = (unsigned long)result; 
  return jresult;
}


SWIGEXPORT std::shared_ptr< MeshEntity > * SWIGSTDCALL CSharp_MeshVertex_SWIGSmartPtrUpcast(std::shared_ptr< MeshVertex > *jarg1) {
    return jarg1 ? new std::shared_ptr< MeshEntity >(*jarg1) : 0;
}

SWIGEXPORT std::shared_ptr< MeshEntity > * SWIGSTDCALL CSharp_MeshEdge_SWIGSmartPtrUpcast(std::shared_ptr< MeshEdge > *jarg1) {
    return jarg1 ? new std::shared_ptr< MeshEntity >(*jarg1) : 0;
}

SWIGEXPORT std::shared_ptr< MeshEntity > * SWIGSTDCALL CSharp_MeshFace_SWIGSmartPtrUpcast(std::shared_ptr< MeshFace > *jarg1) {
    return jarg1 ? new std::shared_ptr< MeshEntity >(*jarg1) : 0;
}

#ifdef __cplusplus
}
#endif

