//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MeshDB {
  public static uint ndof {
    set {
      MeshDBPINVOKE.ndof_set(value);
    } 
    get {
      uint ret = MeshDBPINVOKE.ndof_get();
      return ret;
    } 
  }

  public static readonly int DOF_Free = MeshDBPINVOKE.DOF_Free_get();
  public static readonly int DOF_Zero = MeshDBPINVOKE.DOF_Zero_get();
  public static readonly int DOF_Fixed = MeshDBPINVOKE.DOF_Fixed_get();
}
