//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Mesh : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal Mesh(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Mesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Mesh() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          TransFEPINVOKE.delete_Mesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Mesh() : this(TransFEPINVOKE.new_Mesh(), true) {
  }

  public SWIGTYPE_p_MeshRegion newRegion() {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_newRegion(swigCPtr);
    SWIGTYPE_p_MeshRegion ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_MeshRegion(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshFace newFace() {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_newFace(swigCPtr);
    MeshFace ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshFace(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshEdge newEdge() {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_newEdge(swigCPtr);
    MeshEdge ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshEdge(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshVertex newVertex() {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_newVertex(swigCPtr);
    MeshVertex ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshVertex(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Node newNode() {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_newNode(swigCPtr);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_MeshRegion getRegion(uint n) {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_getRegion(swigCPtr, n);
    SWIGTYPE_p_MeshRegion ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_MeshRegion(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshFace getFace(uint n) {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_getFace(swigCPtr, n);
    MeshFace ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshFace(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshEdge getEdge(uint n) {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_getEdge(swigCPtr, n);
    MeshEdge ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshEdge(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public MeshVertex getVertex(uint n) {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_getVertex(swigCPtr, n);
    MeshVertex ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshVertex(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Node getNode(uint n) {
    global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_getNode(swigCPtr, n);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator getFirstRegion() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator(TransFEPINVOKE.Mesh_getFirstRegion(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator getLastRegion() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshRegion_t_t__iterator(TransFEPINVOKE.Mesh_getLastRegion(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator getFirstFace() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator(TransFEPINVOKE.Mesh_getFirstFace(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator getLastFace() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshFace_t_t__iterator(TransFEPINVOKE.Mesh_getLastFace(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator getFirstEdge() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator(TransFEPINVOKE.Mesh_getFirstEdge(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator getLastEdge() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshEdge_t_t__iterator(TransFEPINVOKE.Mesh_getLastEdge(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator getFirstVertex() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator(TransFEPINVOKE.Mesh_getFirstVertex(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator getLastVertex() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_MeshVertex_t_t__iterator(TransFEPINVOKE.Mesh_getLastVertex(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator getFirstNode() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator(TransFEPINVOKE.Mesh_getFirstNode(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator getLastNode() {
    SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator ret = new SWIGTYPE_p_std__vectorT_std__shared_ptrT_Node_t_t__iterator(TransFEPINVOKE.Mesh_getLastNode(swigCPtr), true);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numRegions() {
    uint ret = TransFEPINVOKE.Mesh_numRegions(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numFaces() {
    uint ret = TransFEPINVOKE.Mesh_numFaces(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numEdges() {
    uint ret = TransFEPINVOKE.Mesh_numEdges(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numVertexes() {
    uint ret = TransFEPINVOKE.Mesh_numVertexes(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint numNodes() {
    uint ret = TransFEPINVOKE.Mesh_numNodes(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void reorder() {
    TransFEPINVOKE.Mesh_reorder(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reorder2() {
    TransFEPINVOKE.Mesh_reorder2(swigCPtr);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
  }

  public void readMesh(string meshfile) {
    TransFEPINVOKE.Mesh_readMesh(swigCPtr, meshfile);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
  }

  public void readAttributes(string attribfile) {
    TransFEPINVOKE.Mesh_readAttributes(swigCPtr, attribfile);
    if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
  }

  public NodePtrVec Nodes {
    set {
      TransFEPINVOKE.Mesh_Nodes_set(swigCPtr, NodePtrVec.getCPtr(value));
      if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_Nodes_get(swigCPtr);
      NodePtrVec ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodePtrVec(cPtr, false);
      if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public MeshFacePtrVec MeshFaces {
    set {
      TransFEPINVOKE.Mesh_MeshFaces_set(swigCPtr, MeshFacePtrVec.getCPtr(value));
      if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      global::System.IntPtr cPtr = TransFEPINVOKE.Mesh_MeshFaces_get(swigCPtr);
      MeshFacePtrVec ret = (cPtr == global::System.IntPtr.Zero) ? null : new MeshFacePtrVec(cPtr, false);
      if (TransFEPINVOKE.SWIGPendingException.Pending) throw TransFEPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}
