//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NodePtrVec : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<Node>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NodePtrVec(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NodePtrVec obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(NodePtrVec obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~NodePtrVec() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TransFE_NativeWrapperPINVOKE.delete_NodePtrVec(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public NodePtrVec(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Node element in c) {
      this.Add(element);
    }
  }

  public NodePtrVec(global::System.Collections.Generic.IEnumerable<Node> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Node element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Node this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Node[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Node[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Node[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Node[] ToArray() {
    Node[] array = new Node[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Node> global::System.Collections.Generic.IEnumerable<Node>.GetEnumerator() {
    return new NodePtrVecEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new NodePtrVecEnumerator(this);
  }

  public NodePtrVecEnumerator GetEnumerator() {
    return new NodePtrVecEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class NodePtrVecEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Node>
  {
    private NodePtrVec collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public NodePtrVecEnumerator(NodePtrVec collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Node Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Node)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_Clear(swigCPtr);
  }

  public void Add(Node x) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_Add(swigCPtr, Node.getCPtr(x));
  }

  private uint size() {
    uint ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_reserve(swigCPtr, n);
  }

  public NodePtrVec() : this(TransFE_NativeWrapperPINVOKE.new_NodePtrVec__SWIG_0(), true) {
  }

  public NodePtrVec(NodePtrVec other) : this(TransFE_NativeWrapperPINVOKE.new_NodePtrVec__SWIG_1(NodePtrVec.getCPtr(other)), true) {
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public NodePtrVec(int capacity) : this(TransFE_NativeWrapperPINVOKE.new_NodePtrVec__SWIG_2(capacity), true) {
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  private Node getitemcopy(int index) {
    global::System.IntPtr cPtr = TransFE_NativeWrapperPINVOKE.NodePtrVec_getitemcopy(swigCPtr, index);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, true);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Node getitem(int index) {
    global::System.IntPtr cPtr = TransFE_NativeWrapperPINVOKE.NodePtrVec_getitem(swigCPtr, index);
    Node ret = (cPtr == global::System.IntPtr.Zero) ? null : new Node(cPtr, true);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Node val) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_setitem(swigCPtr, index, Node.getCPtr(val));
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(NodePtrVec values) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_AddRange(swigCPtr, NodePtrVec.getCPtr(values));
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public NodePtrVec GetRange(int index, int count) {
    global::System.IntPtr cPtr = TransFE_NativeWrapperPINVOKE.NodePtrVec_GetRange(swigCPtr, index, count);
    NodePtrVec ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodePtrVec(cPtr, true);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Node x) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_Insert(swigCPtr, index, Node.getCPtr(x));
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, NodePtrVec values) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_InsertRange(swigCPtr, index, NodePtrVec.getCPtr(values));
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_RemoveAt(swigCPtr, index);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_RemoveRange(swigCPtr, index, count);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public static NodePtrVec Repeat(Node value, int count) {
    global::System.IntPtr cPtr = TransFE_NativeWrapperPINVOKE.NodePtrVec_Repeat(Node.getCPtr(value), count);
    NodePtrVec ret = (cPtr == global::System.IntPtr.Zero) ? null : new NodePtrVec(cPtr, true);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_Reverse__SWIG_1(swigCPtr, index, count);
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, NodePtrVec values) {
    TransFE_NativeWrapperPINVOKE.NodePtrVec_SetRange(swigCPtr, index, NodePtrVec.getCPtr(values));
    if (TransFE_NativeWrapperPINVOKE.SWIGPendingException.Pending) throw TransFE_NativeWrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(Node value) {
    bool ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_Contains(swigCPtr, Node.getCPtr(value));
    return ret;
  }

  public int IndexOf(Node value) {
    int ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_IndexOf(swigCPtr, Node.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(Node value) {
    int ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_LastIndexOf(swigCPtr, Node.getCPtr(value));
    return ret;
  }

  public bool Remove(Node value) {
    bool ret = TransFE_NativeWrapperPINVOKE.NodePtrVec_Remove(swigCPtr, Node.getCPtr(value));
    return ret;
  }

}
