//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TransFE_NativeWrapper {
  public static uint ndof {
    set {
      TransFE_NativeWrapperPINVOKE.ndof_set(value);
    } 
    get {
      uint ret = TransFE_NativeWrapperPINVOKE.ndof_get();
      return ret;
    } 
  }

}
